language: cpp
os: osx
compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew update; fi
  - #if [[ $TRAVIS_OS_NAME == osx && `brew list | grep boost` == '' ]]; then brew install boost; fi
  - #if [[ $TRAVIS_OS_NAME == osx ]]; then brew outdated boost || brew upgrade boost; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep doxygen` == '' ]]; then brew install doxygen; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep cmake` == '' ]]; then brew install cmake; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep ninja` == '' ]]; then brew install ninja; fi
  
before_script:
  - cmake --version
  - cmake -G "Ninja" -DBUILD_TEST=TRUE

script: ninja camptest

after_success: ./test/camptest

notifications:
  email:
    on_failure: always
    
    